name: 'sales_pipeline_dw'
version: '1.0.0'

profile: 'sales_pipeline_dw'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

log-path: logs


models:

  sales_pipeline_dw:

    bronze:
      +materialized: view

    silver:
      +materialized: incremental

    gold:
      dimensions:
        +materialized: table

      facts:
        +materialized: incremental

      marts:
        +materialized: table   


        models:
 