name: DBT CI

on:
push:
branches:
- main

pull_request:

jobs:
dbt-validation:

```
runs-on: ubuntu-latest

steps:

  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - name: Install dbt
    run: |
      pip install dbt-core dbt-postgres

  - name: Install dbt Dependencies
    run: |
      dbt deps \
        --project-dir ./dbt_project \
        --profiles-dir ./dbt_project

  - name: Parse dbt Project
    run: |
      dbt parse \
        --project-dir ./dbt_project \
        --profiles-dir ./dbt_project

  - name: Compile dbt Models
    run: |
      dbt compile \
        --project-dir ./dbt_project \
        --profiles-dir ./dbt_project
```
