name: DBT CI

on:

  push:
    branches:
      - main

  pull_request:

jobs:

  dbt:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-core
          pip install dbt-postgres

      - name: Install Dependencies
        run: dbt deps

      - name: Parse
        run: dbt parse

      - name: Compile
        run: dbt compile

      - name: Test
        run: dbt test