name: dbt CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dbt-validation:
    runs-on: ubuntu-latest
    env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        #POSTGRES_USER: admin
        #POSTGRES_PASSWORD: admin
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}        
        DW_DB: sales_dw
        POSTGRES_SCHEMA: public
        DBT_THREADS: 2
        AIRFLOW_DB: airflow
        DBT_TARGET: dev
        POSTGRES_DB: POSTGRES_DB

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-core dbt-postgres

      - name: Validate dbt Project

        run: |
          cd dbt_project
          dbt deps || true
          dbt parse